// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: curd.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamGreeter_CmsCreate_FullMethodName = "/stream.StreamGreeter/CmsCreate"
	StreamGreeter_CmsDel_FullMethodName    = "/stream.StreamGreeter/CmsDel"
	StreamGreeter_CmsUpdate_FullMethodName = "/stream.StreamGreeter/CmsUpdate"
	StreamGreeter_CmsList_FullMethodName   = "/stream.StreamGreeter/CmsList"
)

// StreamGreeterClient is the client API for StreamGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamGreeterClient interface {
	CmsCreate(ctx context.Context, in *CmsCreateReq, opts ...grpc.CallOption) (*CmsCreateResp, error)
	CmsDel(ctx context.Context, in *CmsDelReq, opts ...grpc.CallOption) (*CmsDelResp, error)
	CmsUpdate(ctx context.Context, in *CmsUpdateReq, opts ...grpc.CallOption) (*CmsUpdateResp, error)
	CmsList(ctx context.Context, in *CmsListReq, opts ...grpc.CallOption) (*CmsListResp, error)
}

type streamGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamGreeterClient(cc grpc.ClientConnInterface) StreamGreeterClient {
	return &streamGreeterClient{cc}
}

func (c *streamGreeterClient) CmsCreate(ctx context.Context, in *CmsCreateReq, opts ...grpc.CallOption) (*CmsCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CmsCreateResp)
	err := c.cc.Invoke(ctx, StreamGreeter_CmsCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) CmsDel(ctx context.Context, in *CmsDelReq, opts ...grpc.CallOption) (*CmsDelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CmsDelResp)
	err := c.cc.Invoke(ctx, StreamGreeter_CmsDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) CmsUpdate(ctx context.Context, in *CmsUpdateReq, opts ...grpc.CallOption) (*CmsUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CmsUpdateResp)
	err := c.cc.Invoke(ctx, StreamGreeter_CmsUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamGreeterClient) CmsList(ctx context.Context, in *CmsListReq, opts ...grpc.CallOption) (*CmsListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CmsListResp)
	err := c.cc.Invoke(ctx, StreamGreeter_CmsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamGreeterServer is the server API for StreamGreeter service.
// All implementations must embed UnimplementedStreamGreeterServer
// for forward compatibility.
type StreamGreeterServer interface {
	CmsCreate(context.Context, *CmsCreateReq) (*CmsCreateResp, error)
	CmsDel(context.Context, *CmsDelReq) (*CmsDelResp, error)
	CmsUpdate(context.Context, *CmsUpdateReq) (*CmsUpdateResp, error)
	CmsList(context.Context, *CmsListReq) (*CmsListResp, error)
	mustEmbedUnimplementedStreamGreeterServer()
}

// UnimplementedStreamGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamGreeterServer struct{}

func (UnimplementedStreamGreeterServer) CmsCreate(context.Context, *CmsCreateReq) (*CmsCreateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CmsCreate not implemented")
}
func (UnimplementedStreamGreeterServer) CmsDel(context.Context, *CmsDelReq) (*CmsDelResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CmsDel not implemented")
}
func (UnimplementedStreamGreeterServer) CmsUpdate(context.Context, *CmsUpdateReq) (*CmsUpdateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CmsUpdate not implemented")
}
func (UnimplementedStreamGreeterServer) CmsList(context.Context, *CmsListReq) (*CmsListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CmsList not implemented")
}
func (UnimplementedStreamGreeterServer) mustEmbedUnimplementedStreamGreeterServer() {}
func (UnimplementedStreamGreeterServer) testEmbeddedByValue()                       {}

// UnsafeStreamGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamGreeterServer will
// result in compilation errors.
type UnsafeStreamGreeterServer interface {
	mustEmbedUnimplementedStreamGreeterServer()
}

func RegisterStreamGreeterServer(s grpc.ServiceRegistrar, srv StreamGreeterServer) {
	// If the following call panics, it indicates UnimplementedStreamGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamGreeter_ServiceDesc, srv)
}

func _StreamGreeter_CmsCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmsCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).CmsCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_CmsCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).CmsCreate(ctx, req.(*CmsCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_CmsDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmsDelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).CmsDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_CmsDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).CmsDel(ctx, req.(*CmsDelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_CmsUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmsUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).CmsUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_CmsUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).CmsUpdate(ctx, req.(*CmsUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamGreeter_CmsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamGreeterServer).CmsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamGreeter_CmsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamGreeterServer).CmsList(ctx, req.(*CmsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamGreeter_ServiceDesc is the grpc.ServiceDesc for StreamGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamGreeter",
	HandlerType: (*StreamGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CmsCreate",
			Handler:    _StreamGreeter_CmsCreate_Handler,
		},
		{
			MethodName: "CmsDel",
			Handler:    _StreamGreeter_CmsDel_Handler,
		},
		{
			MethodName: "CmsUpdate",
			Handler:    _StreamGreeter_CmsUpdate_Handler,
		},
		{
			MethodName: "CmsList",
			Handler:    _StreamGreeter_CmsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "curd.proto",
}
