// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: curd.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmsCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	ViewCount     int64                  `protobuf:"varint,5,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	Creator       int64                  `protobuf:"varint,6,opt,name=creator,proto3" json:"creator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmsCreateReq) Reset() {
	*x = CmsCreateReq{}
	mi := &file_curd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmsCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsCreateReq) ProtoMessage() {}

func (x *CmsCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_curd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsCreateReq.ProtoReflect.Descriptor instead.
func (*CmsCreateReq) Descriptor() ([]byte, []int) {
	return file_curd_proto_rawDescGZIP(), []int{0}
}

func (x *CmsCreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CmsCreateReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CmsCreateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CmsCreateReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CmsCreateReq) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *CmsCreateReq) GetCreator() int64 {
	if x != nil {
		return x.Creator
	}
	return 0
}

type CmsCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmsCreateResp) Reset() {
	*x = CmsCreateResp{}
	mi := &file_curd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmsCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsCreateResp) ProtoMessage() {}

func (x *CmsCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_curd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsCreateResp.ProtoReflect.Descriptor instead.
func (*CmsCreateResp) Descriptor() ([]byte, []int) {
	return file_curd_proto_rawDescGZIP(), []int{1}
}

func (x *CmsCreateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CmsCreateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CmsDelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmsDelReq) Reset() {
	*x = CmsDelReq{}
	mi := &file_curd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmsDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsDelReq) ProtoMessage() {}

func (x *CmsDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_curd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsDelReq.ProtoReflect.Descriptor instead.
func (*CmsDelReq) Descriptor() ([]byte, []int) {
	return file_curd_proto_rawDescGZIP(), []int{2}
}

func (x *CmsDelReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CmsDelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmsDelResp) Reset() {
	*x = CmsDelResp{}
	mi := &file_curd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmsDelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsDelResp) ProtoMessage() {}

func (x *CmsDelResp) ProtoReflect() protoreflect.Message {
	mi := &file_curd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsDelResp.ProtoReflect.Descriptor instead.
func (*CmsDelResp) Descriptor() ([]byte, []int) {
	return file_curd_proto_rawDescGZIP(), []int{3}
}

func (x *CmsDelResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CmsDelResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CmsUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ViewCount     int64                  `protobuf:"varint,6,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	Creator       int64                  `protobuf:"varint,7,opt,name=creator,proto3" json:"creator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmsUpdateReq) Reset() {
	*x = CmsUpdateReq{}
	mi := &file_curd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmsUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsUpdateReq) ProtoMessage() {}

func (x *CmsUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_curd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsUpdateReq.ProtoReflect.Descriptor instead.
func (*CmsUpdateReq) Descriptor() ([]byte, []int) {
	return file_curd_proto_rawDescGZIP(), []int{4}
}

func (x *CmsUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CmsUpdateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CmsUpdateReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CmsUpdateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CmsUpdateReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CmsUpdateReq) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *CmsUpdateReq) GetCreator() int64 {
	if x != nil {
		return x.Creator
	}
	return 0
}

type CmsUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmsUpdateResp) Reset() {
	*x = CmsUpdateResp{}
	mi := &file_curd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmsUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsUpdateResp) ProtoMessage() {}

func (x *CmsUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_curd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsUpdateResp.ProtoReflect.Descriptor instead.
func (*CmsUpdateResp) Descriptor() ([]byte, []int) {
	return file_curd_proto_rawDescGZIP(), []int{5}
}

func (x *CmsUpdateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CmsUpdateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CmsListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmsListReq) Reset() {
	*x = CmsListReq{}
	mi := &file_curd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsListReq) ProtoMessage() {}

func (x *CmsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_curd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsListReq.ProtoReflect.Descriptor instead.
func (*CmsListReq) Descriptor() ([]byte, []int) {
	return file_curd_proto_rawDescGZIP(), []int{6}
}

func (x *CmsListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CmsListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CmsListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Cms                 `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmsListResp) Reset() {
	*x = CmsListResp{}
	mi := &file_curd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsListResp) ProtoMessage() {}

func (x *CmsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_curd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsListResp.ProtoReflect.Descriptor instead.
func (*CmsListResp) Descriptor() ([]byte, []int) {
	return file_curd_proto_rawDescGZIP(), []int{7}
}

func (x *CmsListResp) GetList() []*Cms {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CmsListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CmsListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Cms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CategoryName  string                 `protobuf:"bytes,3,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ViewCount     int64                  `protobuf:"varint,6,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	Creator       int64                  `protobuf:"varint,7,opt,name=creator,proto3" json:"creator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cms) Reset() {
	*x = Cms{}
	mi := &file_curd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cms) ProtoMessage() {}

func (x *Cms) ProtoReflect() protoreflect.Message {
	mi := &file_curd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cms.ProtoReflect.Descriptor instead.
func (*Cms) Descriptor() ([]byte, []int) {
	return file_curd_proto_rawDescGZIP(), []int{8}
}

func (x *Cms) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cms) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Cms) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Cms) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Cms) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Cms) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Cms) GetCreator() int64 {
	if x != nil {
		return x.Creator
	}
	return 0
}

var File_curd_proto protoreflect.FileDescriptor

const file_curd_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"curd.proto\x12\x06stream\"\xae\x01\n" +
	"\fCmsCreateReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x1c\n" +
	"\tviewCount\x18\x05 \x01(\x03R\tviewCount\x12\x18\n" +
	"\acreator\x18\x06 \x01(\x03R\acreator\"5\n" +
	"\rCmsCreateResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1b\n" +
	"\tCmsDelReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\n" +
	"CmsDelResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xbe\x01\n" +
	"\fCmsUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x1c\n" +
	"\tviewCount\x18\x06 \x01(\x03R\tviewCount\x12\x18\n" +
	"\acreator\x18\a \x01(\x03R\acreator\"5\n" +
	"\rCmsUpdateResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"4\n" +
	"\n" +
	"CmsListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"T\n" +
	"\vCmsListResp\x12\x1f\n" +
	"\x04list\x18\x01 \x03(\v2\v.stream.CmsR\x04list\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\xb9\x01\n" +
	"\x03Cms\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\"\n" +
	"\fcategoryName\x18\x03 \x01(\tR\fcategoryName\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x1c\n" +
	"\tviewCount\x18\x06 \x01(\x03R\tviewCount\x12\x18\n" +
	"\acreator\x18\a \x01(\x03R\acreator2\xe8\x01\n" +
	"\rStreamGreeter\x128\n" +
	"\tCmsCreate\x12\x14.stream.CmsCreateReq\x1a\x15.stream.CmsCreateResp\x12/\n" +
	"\x06CmsDel\x12\x11.stream.CmsDelReq\x1a\x12.stream.CmsDelResp\x128\n" +
	"\tCmsUpdate\x12\x14.stream.CmsUpdateReq\x1a\x15.stream.CmsUpdateResp\x122\n" +
	"\aCmsList\x12\x12.stream.CmsListReq\x1a\x13.stream.CmsListRespB\x04Z\x02./b\x06proto3"

var (
	file_curd_proto_rawDescOnce sync.Once
	file_curd_proto_rawDescData []byte
)

func file_curd_proto_rawDescGZIP() []byte {
	file_curd_proto_rawDescOnce.Do(func() {
		file_curd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_curd_proto_rawDesc), len(file_curd_proto_rawDesc)))
	})
	return file_curd_proto_rawDescData
}

var file_curd_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_curd_proto_goTypes = []any{
	(*CmsCreateReq)(nil),  // 0: stream.CmsCreateReq
	(*CmsCreateResp)(nil), // 1: stream.CmsCreateResp
	(*CmsDelReq)(nil),     // 2: stream.CmsDelReq
	(*CmsDelResp)(nil),    // 3: stream.CmsDelResp
	(*CmsUpdateReq)(nil),  // 4: stream.CmsUpdateReq
	(*CmsUpdateResp)(nil), // 5: stream.CmsUpdateResp
	(*CmsListReq)(nil),    // 6: stream.CmsListReq
	(*CmsListResp)(nil),   // 7: stream.CmsListResp
	(*Cms)(nil),           // 8: stream.Cms
}
var file_curd_proto_depIdxs = []int32{
	8, // 0: stream.CmsListResp.list:type_name -> stream.Cms
	0, // 1: stream.StreamGreeter.CmsCreate:input_type -> stream.CmsCreateReq
	2, // 2: stream.StreamGreeter.CmsDel:input_type -> stream.CmsDelReq
	4, // 3: stream.StreamGreeter.CmsUpdate:input_type -> stream.CmsUpdateReq
	6, // 4: stream.StreamGreeter.CmsList:input_type -> stream.CmsListReq
	1, // 5: stream.StreamGreeter.CmsCreate:output_type -> stream.CmsCreateResp
	3, // 6: stream.StreamGreeter.CmsDel:output_type -> stream.CmsDelResp
	5, // 7: stream.StreamGreeter.CmsUpdate:output_type -> stream.CmsUpdateResp
	7, // 8: stream.StreamGreeter.CmsList:output_type -> stream.CmsListResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_curd_proto_init() }
func file_curd_proto_init() {
	if File_curd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_curd_proto_rawDesc), len(file_curd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_curd_proto_goTypes,
		DependencyIndexes: file_curd_proto_depIdxs,
		MessageInfos:      file_curd_proto_msgTypes,
	}.Build()
	File_curd_proto = out.File
	file_curd_proto_goTypes = nil
	file_curd_proto_depIdxs = nil
}
